### ISSUE TITLE
Problems with Python 3.11?

### ISSUE THREAD

**Issue by skroecher-gingco** [ionos-cloud/module-ansible#207]
## Description
I am not familiar with Python, so this may not be a real bug. 
I don't get the ionoscloudsdk.ionoscloud ansible module work on platforms with Python 3.11.x. I get nearly identical error messages from python. 
It works fine on a platform with Python 3.9.x.

## Expected behavior
With a simple playbook - see below - I try to create a datacenter, which fails

## Environment
It's **working** on:
* Debian 11, ansible 2.10.8, Python 3.9.2, ionoscloudsdk.ionoscloud module 7.4.1

**NOT** working on:
* Debian 12, ansible core 2.14.3, Python 3.11.2, ionoscloudsdk.ionoscloud module 7.4.1
* Alpine Linux 3.19 (Semaphore UI Docker Container),  ansible [core 2.16.9], Python 3.11.9, ionoscloudsdk.ionoscloud module 7.4.1

## Configuration Files
---Playbook---
```
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    dc_name: "DUMMYDATACENTER"
    dc_description: ""
    dc_location: "de/fra"

  tasks:
  - name: Create datacenter
    ionoscloudsdk.ionoscloud.datacenter:
        name: "{{ dc_name }}"
        description: "{{ dc_description }}"
        location: "{{ dc_location }}"
        wait: true
    register: datacenter_response

```

## Error and Debug Output

Debian 12:
```
TASK [Create datacenter] ********************************************************************************************************************************************************************************************************************
task path: /opt/git/ansible-test/playbooks/ionos/create-datacenter.yaml:11
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461 `" && echo ansible-tmp-1724165214.5015018-351717-193722452181461="` echo /root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/ionoscloudsdk/ionoscloud/plugins/modules/datacenter.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-351713nw9y2cjd/tmph35qjcqr TO /root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/AnsiballZ_datacenter.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/ /root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/AnsiballZ_datacenter.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/AnsiballZ_datacenter.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/AnsiballZ_datacenter.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/AnsiballZ_datacenter.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/AnsiballZ_datacenter.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ionoscloudsdk.ionoscloud.plugins.modules.datacenter', init_globals=dict(_module_fqn='ansible_collections.ionoscloudsdk.ionoscloud.plugins.modules.datacenter', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_ionoscloudsdk.ionoscloud.datacenter_payload_as3ky8s0/ansible_ionoscloudsdk.ionoscloud.datacenter_payload.zip/ansible_collections/ionoscloudsdk/ionoscloud/plugins/modules/datacenter.py", line 34, in <module>
NameError: name 'sdk_version' is not defined
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/AnsiballZ_datacenter.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/AnsiballZ_datacenter.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1724165214.5015018-351717-193722452181461/AnsiballZ_datacenter.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ionoscloudsdk.ionoscloud.plugins.modules.datacenter', init_globals=dict(_module_fqn='ansible_collections.ionoscloudsdk.ionoscloud.plugins.modules.datacenter', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_ionoscloudsdk.ionoscloud.datacenter_payload_as3ky8s0/ansible_ionoscloudsdk.ionoscloud.datacenter_payload.zip/ansible_collections/ionoscloudsdk/ionoscloud/plugins/modules/datacenter.py\", line 34, in <module>\nNameError: name 'sdk_version' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Semaphore UI Container:

```
1:29:56 PM
TASK [Create datacenter] *******************************************************
1:29:56 PM
task path: /tmp/semaphore/repository_1_4/playbooks/ionos/create-datacenter.yaml:11
1:29:56 PM
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
1:29:56 PM
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
1:29:56 PM
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728 `" && echo ansible-tmp-1724153396.3358188-103308-80014192353728="` echo /root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728 `" ) && sleep 0'
1:29:56 PM
Using module file /tmp/semaphore/.ansible/collections/ansible_collections/ionoscloudsdk/ionoscloud/plugins/modules/datacenter.py
1:29:56 PM
<127.0.0.1> PUT /tmp/semaphore/.ansible/tmp/ansible-local-103305vtju4m15/tmpdcueg91z TO /root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/AnsiballZ_datacenter.py
1:29:56 PM
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/ /root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/AnsiballZ_datacenter.py && sleep 0'
1:29:56 PM
<127.0.0.1> EXEC /bin/sh -c '/opt/semaphore/apps/ansible/9.4.0/venv/bin/python3 /root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/AnsiballZ_datacenter.py && sleep 0'
1:29:56 PM
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/ > /dev/null 2>&1 && sleep 0'
1:29:56 PM
The full traceback is:
1:29:56 PM
Traceback (most recent call last):
1:29:56 PM
  File "/root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/AnsiballZ_datacenter.py", line 107, in 
1:29:56 PM
    _ansiballz_main()
1:29:56 PM
  File "/root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/AnsiballZ_datacenter.py", line 99, in _ansiballz_main
1:29:56 PM
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
1:29:56 PM
  File "/root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/AnsiballZ_datacenter.py", line 47, in invoke_module
1:29:56 PM
    runpy.run_module(mod_name='ansible_collections.ionoscloudsdk.ionoscloud.plugins.modules.datacenter', init_globals=dict(_module_fqn='ansible_collections.ionoscloudsdk.ionoscloud.plugins.modules.datacenter', _modlib_path=modlib_path),
1:29:56 PM
  File "", line 226, in run_module
1:29:56 PM
  File "", line 98, in _run_module_code
1:29:56 PM
  File "", line 88, in _run_code
1:29:56 PM
  File "/tmp/ansible_ionoscloudsdk.ionoscloud.datacenter_payload_88rsaezy/ansible_ionoscloudsdk.ionoscloud.datacenter_payload.zip/ansible_collections/ionoscloudsdk/ionoscloud/plugins/modules/datacenter.py", line 32, in 
1:29:56 PM
NameError: name 'sdk_version' is not defined
1:29:56 PM
fatal: [localhost]: FAILED! => changed=false 
1:29:56 PM
  module_stderr: |-
1:29:56 PM
    Traceback (most recent call last):
1:29:56 PM
      File "/root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/AnsiballZ_datacenter.py", line 107, in 
1:29:56 PM
        _ansiballz_main()
1:29:56 PM
      File "/root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/AnsiballZ_datacenter.py", line 99, in _ansiballz_main
1:29:56 PM
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
1:29:56 PM
      File "/root/.ansible/tmp/ansible-tmp-1724153396.3358188-103308-80014192353728/AnsiballZ_datacenter.py", line 47, in invoke_module
1:29:56 PM
        runpy.run_module(mod_name='ansible_collections.ionoscloudsdk.ionoscloud.plugins.modules.datacenter', init_globals=dict(_module_fqn='ansible_collections.ionoscloudsdk.ionoscloud.plugins.modules.datacenter', _modlib_path=modlib_path),
1:29:56 PM
      File "", line 226, in run_module
1:29:56 PM
      File "", line 98, in _run_module_code
1:29:56 PM
      File "", line 88, in _run_code
1:29:56 PM
      File "/tmp/ansible_ionoscloudsdk.ionoscloud.datacenter_payload_88rsaezy/ansible_ionoscloudsdk.ionoscloud.datacenter_payload.zip/ansible_collections/ionoscloudsdk/ionoscloud/plugins/modules/datacenter.py", line 32, in 
1:29:56 PM
    NameError: name 'sdk_version' is not defined
1:29:56 PM
  module_stdout: ''
1:29:56 PM
  msg: |-
1:29:56 PM
    MODULE FAILURE
1:29:56 PM
    See stdout/stderr for the exact error
1:29:56 PM
  rc: 1
```

**Comment by rmocanu-ionos** [comment]
Thank you for reaching out. It seems that using Python 3.11.9 is working on my end. From the error message you're seeing, it appears there might be an issue with our SDK not being installed correctly (we'll work on making this clearer in the future). Could you please ensure that the SDK is installed properly and that you're able to import it without any issues?

If you continue to encounter problems, feel free to provide more details, and we'll be happy to assist further.

**Comment by rmocanu-ionos** [comment]
You’re welcome! I’m glad I could assist. If you have any more questions or need further help, feel free to ask.
